### ISSUE TITLE
CONSTRUCT calls

### ISSUE THREAD

**Issue by fils** [knakk/sparql#2]
Is it possible to use CONSTRUCT or DESCRIBE calls in some way via this library.  Or is focused on SELECT calls only?    It's very valuable, but I was curious if we could do these other SPARQL queries.

**Comment by boutros** [comment]
Thanks for you interest!

I have only used it for SELECT calls until now, but it shouldn't be much work to make some convenience functions issuing DESCRIBE/CONSTRUCT queries, returning `[]rdf.Triple` instead of the result sets.

If you want to have a go at it, please do, or I will get around to it, in a not to distant future:)

**Comment by fils** [comment]
Thanks for getting back to me.   Good to know I am not missing something.  A friend and I are working on some go based go to do a little simple gateways from our RDF triple stores to JSON_LD via the go-restful library.    I'll let him know the status.  We might poke around a bit on it, but we may not have the golang skills necessary to do this.  We will look though.  

Thanks..  I use your package with my SELECT calls and it's wonderful!   Far better than the stuff I rolled myself for this.

**Comment by boutros** [comment]
Hi again,
I went ahead and added a `Construct` method to `Repo`, which returns a set of triples, and not a query-result set:
https://github.com/knakk/sparql/commit/bde8b437845a17a86b68e9fe564b2feda9525598
